# Uncomment the next line to define a global platform for your project
platform :ios,'10.0'

target 'Moviebuff' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 	pod 'RxSwift',                 '~> 5.0'
    	pod 'RxCocoa',                 '~> 5.0'
    	pod 'RxDataSources',           	'~> 4.0'
    	pod 'RxGesture',               '~> 3.0'
   	pod 'RxOptional',              '~> 4.0'
	pod 'Moya', 			'~> 13.0'
	pod 'HandyJSON', 		'~> 5.0'

  use_frameworks!

  # Pods for Moviebuff

  target 'MoviebuffTests' do
    inherit! :search_paths
   	pod 'Quick', '~> 2.1'
	pod 'Nimble', '~> 8.0'
	pod 'RxBlocking', '~> 5'
	pod 'RxTest',     '~> 5'
  end

  target 'MoviebuffUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
