# Uncomment the next line to define a global platform for your project
platform :ios,'10.0'

target 'Moviebuff' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 	pod 'RxSwift',                 '~> 4.0'
    	pod 'RxCocoa',                 '~> 4.0'
    	pod 'RxDataSources',           	'~> 3.0'
    	pod 'RxGesture',               '~> 2.0'
   	pod 'RxOptional',              '~> 3.0'
	pod 'Moya/RxSwift',            '~> 13'
	pod 'HandyJSON', 		'~> 5.0'

  use_frameworks!

  # Pods for Moviebuff

  target 'MoviebuffTests' do
    inherit! :search_paths
		pod 'Quick', '~> 2.1'
		pod 'Nimble', '~> 8.0'
		pod 'RxBlocking', '~> 4.0'
		pod 'RxTest',     '~> 4.0'
  end

  target 'MoviebuffUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
