# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moviebuff' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 	pod 'RxSwift'  
	pod 'RxCocoa'             
	pod 'RxDataSources'        
    	pod 'RxGesture'        
	pod 'RxOptional'
	pod 'Moya/RxSwift'  

  use_frameworks!

  # Pods for Moviebuff

  target 'MoviebuffTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviebuffUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
